test

diff --git a/.gitlab/pipeline/test.yml b/.gitlab/pipeline/test.yml
--- a/.gitlab/pipeline/test.yml
+++ b/.gitlab/pipeline/test.yml
@@ -238,6 +238,8 @@ test-deterministic-wasm:
 
 cargo-check-benches:
   stage: test
+  artifacts:
+    expire_in: 10 days
   variables:
     CI_JOB_NAME: "cargo-check-benches"
   extends:
@@ -304,14 +306,14 @@ node-bench-regression-guard:
   variables:
     CI_IMAGE: "paritytech/node-bench-regression-guard:latest"
     # current git limit is 20, set to 1000 to avoid failures (gitlab removes old artifacts)
-    GIT_DEPTH: 1000
-    GIT_STRATEGY: fetch
+    # GIT_DEPTH: 1000
+    # GIT_STRATEGY: fetch
   before_script: [""]
   script:
-    - if [ $(ls -la artifacts/benches/ | grep master | wc -l) == 0 ]; then
-      echo "Couldn't find master artifacts, consider increasing GIT_LIMIT variable";
-      exit 1;
-      fi
+    # - if [ $(ls -la artifacts/benches/ | grep master | wc -l) == 0 ]; then
+    #   echo "Couldn't find master artifacts, consider increasing GIT_LIMIT variable";
+    #   exit 1;
+    #   fi
     - echo "------- IMPORTANT -------"
     - echo "node-bench-regression-guard depends on the results of a cargo-check-benches job"
     - echo "In case of this job failure, check your pipeline's cargo-check-benches"
