ci: process logs for zombienet-sdk tests

diff --git a/.github/actions/zombienet-sdk/action.yml b/.github/actions/zombienet-sdk/action.yml
--- a/.github/actions/zombienet-sdk/action.yml
+++ b/.github/actions/zombienet-sdk/action.yml
@@ -125,6 +125,20 @@ runs:
           ls -ltr ./artifacts
           cargo nextest run --archive-file ./artifacts/${PREFIX}-zombienet-tests.tar.zst --no-capture -- ${TEST_NAME}
 
+    - name: process_logs
+      if: ${{ ! cancelled() }}
+      shell: bash
+      run: |
+        echo "Processing log files"
+        echo "::group::Logs"
+        # do not fail the whole run if this step fails
+        if ! ./.github/scripts/process-logs-zombienet-sdk.sh ; then
+          echo "::endgroup::"
+          echo "::warning ::WARNING: Failed to process logs"
+        else
+          echo "::endgroup::"
+        fi
+
     - name: upload_logs
       uses: actions/upload-artifact@v4
       if: ${{ ! cancelled() }}
