merge with `master`

diff --git a/.github/workflows/check-runtime-compatibility.yml b/.github/workflows/check-runtime-compatibility.yml
--- a/.github/workflows/check-runtime-compatibility.yml
+++ b/.github/workflows/check-runtime-compatibility.yml
@@ -39,6 +39,7 @@ jobs:
             bridge-hub-westend,
             collectives-westend,
             coretime-westend,
+            people-westend,
           ]
         include:
           - network: westend
@@ -61,9 +62,13 @@ jobs:
             package: coretime-westend-runtime
             wasm: coretime_westend_runtime.compact.compressed.wasm
             uri: "wss://westend-coretime-rpc.polkadot.io:443"
+          - network: people-westend
+            package: people-westend-runtime
+            wasm: people_westend_runtime.compact.compressed.wasm
+            uri: "wss://westend-people-rpc.polkadot.io:443"
     steps:
       - name: Checkout
-        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
 
       - name: Build Runtime
         id: build-runtime
@@ -72,7 +77,7 @@ jobs:
           forklift cargo build --release --locked -p ${{ matrix.package }} --features on-chain-release-build -q
 
       - name: Setup Node.js
-        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
+        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
         with:
           node-version: "24.x"
           registry-url: "https://npm.pkg.github.com"
@@ -81,7 +86,16 @@ jobs:
         id: check-compatibility
         run: |
           echo "---------- Checking runtime compatibility for ${{ matrix.network }} ----------"
-          npx @polkadot-api/check-runtime@latest problems ${{ matrix.uri }} --wasm ./target/release/wbuild/${{ matrix.package }}/${{ matrix.wasm }}
+          set +e
+          # check-runtime hangs indefinitely if the RPC node is unreachable.
+          timeout 120 npx @polkadot-api/check-runtime@latest problems ${{ matrix.uri }} --wasm ./target/release/wbuild/${{ matrix.package }}/${{ matrix.wasm }}
+          EXIT_CODE=$?
+          set -e
+          # When the time limit is reached, timeout returns exit code 124
+          if [ $EXIT_CODE -eq 124 ]; then
+            echo "::error::Timed out connecting to ${{ matrix.uri }} for ${{ matrix.network }}"
+          fi
+          exit $EXIT_CODE
 
       - name: Stop all workflows if failed
         if: ${{ failure() && (steps.build-runtime.conclusion == 'failure' || steps.check-compatibility.conclusion == 'failure') }}
