fix bench command recognition in if statement

diff --git a/.github/workflows/check-frame-omni-bencher.yml b/.github/workflows/check-frame-omni-bencher.yml
--- a/.github/workflows/check-frame-omni-bencher.yml
+++ b/.github/workflows/check-frame-omni-bencher.yml
@@ -95,14 +95,18 @@ jobs:
         run: |
           RUNTIME_BLOB_NAME=$(echo $PACKAGE_NAME | sed 's/-/_/g').compact.compressed.wasm
           RUNTIME_BLOB_PATH=./target/release/wbuild/$PACKAGE_NAME/$RUNTIME_BLOB_NAME
+          BENCH_CMD=${{ matrix.bench_cmd }}
           forklift cargo build --release --locked -p $PACKAGE_NAME -p frame-omni-bencher --features=${{ matrix.runtime.bench_features }} --quiet
           echo "Running short ${{ matrix.bench_cmd }} benchmarking for PACKAGE_NAME=$PACKAGE_NAME and RUNTIME_BLOB_PATH=$RUNTIME_BLOB_PATH"
           ls -lrt $RUNTIME_BLOB_PATH
           
-          if [ "${{ matrix.bench_cmd }}" == "pallet" ]; then
+          if [[ "$BENCH_CMD" == "pallet" ]]; then
             cmd="./target/release/frame-omni-bencher v1 benchmark pallet --runtime $RUNTIME_BLOB_PATH --all --steps 2 --repeat 1 $FLAGS"
-          elif [ "${{ matrix.bench_cmd }}" == "overhead" ]; then
+          elif [[ "$BENCH_CMD" == "overhead" ]]; then
             cmd="./target/release/frame-omni-bencher v1 benchmark overhead --runtime $RUNTIME_BLOB_PATH"
+          else
+            echo "Error: Unknown BENCH_CMD value: $BENCH_CMD"
+            exit 1
           fi
 
           echo "Running command: $cmd"
