Fix runtime migrations check
- On the scheduled run only download the snapshot and not try to run the migration checks
- The job should fail when one of the migration checks was cancelled (because of timeout for example)
- Increase the timeout to 120 min, because sometimes it is slower to download the snapshot

diff --git a/.github/workflows/check-runtime-migration.yml b/.github/workflows/check-runtime-migration.yml
--- a/.github/workflows/check-runtime-migration.yml
+++ b/.github/workflows/check-runtime-migration.yml
@@ -31,7 +31,7 @@ jobs:
     if: ${{ needs.preflight.outputs.changes_rust }}
     # We need to set this to rather long to allow the snapshot to be created, but the average time
     # should be much lower.
-    timeout-minutes: 60
+    timeout-minutes: 120
     needs: [preflight]
     container:
       image: ${{ needs.preflight.outputs.IMAGE }}
@@ -106,12 +106,14 @@ jobs:
           ./try-runtime create-snapshot --uri ${{ matrix.uri }} snapshot.raw
 
       - name: Build Runtime
+        if: ${{ github.event_name != 'schedule' }}
         id: required1
         run: |
           echo "---------- Building ${{ matrix.package }} runtime ----------"
           forklift cargo build --release --locked -p ${{ matrix.package }} --features try-runtime -q
 
       - name: Run Check
+        if: ${{ github.event_name != 'schedule' }}
         id: required2
         run: |
           echo "Running ${{ matrix.network }} runtime migration check"
@@ -124,7 +126,7 @@ jobs:
           sleep 5
 
       - name: Stop all workflows if failed
-        if: ${{ failure() && (steps.required1.conclusion == 'failure' || steps.required2.conclusion == 'failure') }}
+        if: ${{ failure() && github.event_name != 'schedule' && (steps.required1.conclusion == 'failure' || steps.required2.conclusion == 'failure') }}
         uses: ./.github/actions/workflow-stopper
         with:
           app-id: ${{ secrets.WORKFLOW_STOPPER_RUNNER_APP_ID }}
@@ -137,13 +139,17 @@ jobs:
     name: All runtime migrations passed
     # If any new job gets added, be sure to add it to this array
     needs: [check-runtime-migration]
-    if: always() && !cancelled()
+    if: always() && !cancelled() && github.event_name != 'schedule'
     steps:
       - run: |
           tee resultfile <<< '${{ toJSON(needs) }}'
           FAILURES=$(cat resultfile | grep '"result": "failure"' | wc -l)
+          CANCELLED=$(cat resultfile | grep '"result": "cancelled"' | wc -l)
           if [ $FAILURES -gt 0 ]; then
             echo "### At least one required job failed ❌" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          elif [ $CANCELLED -gt 0 ]; then
+            echo "### At least one required job was cancelled ❌" >> $GITHUB_STEP_SUMMARY
             exit 1
           else
             echo '### Good job! All the required jobs passed 🚀' >> $GITHUB_STEP_SUMMARY
