Revert "Bring `TransactionExtension` branch up-to-date (#2717)"
This reverts commit 443d0e9d68302c79591a9b945244cdb35d357023.

diff --git a/.github/workflows/check-prdoc.yml b/.github/workflows/check-prdoc.yml
--- a/.github/workflows/check-prdoc.yml
+++ b/.github/workflows/check-prdoc.yml
@@ -6,27 +6,26 @@ on:
   merge_group:
 
 env:
-  IMAGE: docker.io/paritytech/prdoc:v0.0.7
+  IMAGE: paritytech/prdoc:v0.0.5
   API_BASE: https://api.github.com/repos
   REPO: ${{ github.repository }}
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   GITHUB_PR: ${{ github.event.pull_request.number }}
+  MOUNT: /prdoc
   ENGINE: docker
-  PRDOC_DOC: https://github.com/paritytech/polkadot-sdk/blob/master/docs/contributor/prdoc.md
 
 jobs:
   check-prdoc:
     runs-on: ubuntu-latest
     steps:
-      # we cannot show the version in this step (ie before checking out the repo)
-      # due to https://github.com/paritytech/prdoc/issues/15
       - name: Skip merge queue
         if: ${{ contains(github.ref, 'gh-readonly-queue') }}
         run: exit 0
       - name: Pull image
         run: |
           echo "Pulling $IMAGE"
-          $ENGINE pull $IMAGE
+          docker pull $IMAGE
+          docker run --rm $IMAGE --version
 
       - name: Check if PRdoc is required
         id: get-labels
@@ -37,29 +36,18 @@ jobs:
           echo "Labels: ${labels}"
           echo "labels=${labels}" >> "$GITHUB_OUTPUT"
 
-      - name: Checkout repo
-        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
-
-      - name: Check PRDoc version
-        run: |
-          $ENGINE run --rm -v $PWD:/repo $IMAGE --version
-
-      - name: Early exit if PR is silent
+      - name: No PRdoc required
         if: ${{ contains(steps.get-labels.outputs.labels, 'R0') }}
         run: |
-          hits=$(find prdoc -name "pr_$GITHUB_PR*.prdoc" | wc -l)
-          if (( hits > 0 )); then
-            echo "PR detected as silent, but a PRDoc was found, checking it as information"
-            $ENGINE run --rm -v $PWD:/repo $IMAGE check -n ${GITHUB_PR} || echo "Ignoring failure"
-          else
-            echo "PR detected as silent, no PRDoc found, exiting..."
-          fi
-          echo "If you want to add a PRDoc, please refer to $PRDOC_DOC"
+          echo "PR detected as silent, no PRdoc is required, exiting..."
           exit 0
+
+      - name: Checkout repo
+        if: ${{ !contains(steps.get-labels.outputs.labels, 'R0') }}
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
 
       - name: PRdoc check for PR#${{ github.event.pull_request.number }}
         if: ${{ !contains(steps.get-labels.outputs.labels, 'R0') }}
         run: |
-          echo "Checking for PR#${GITHUB_PR}"
-          echo "You can find more information about PRDoc at $PRDOC_DOC"
-          $ENGINE run --rm -v $PWD:/repo $IMAGE check -n ${GITHUB_PR}
+          echo "Checking for PR#${GITHUB_PR} in $MOUNT"
+          $ENGINE run --rm -v $PWD/prdoc:/doc $IMAGE check -n ${GITHUB_PR} || true
