fix confirm-required-checks-quick-jobs-passed

diff --git a/.github/workflows/checks-quick.yml b/.github/workflows/checks-quick.yml
--- a/.github/workflows/checks-quick.yml
+++ b/.github/workflows/checks-quick.yml
@@ -196,5 +196,14 @@ jobs:
       - check-markdown
       - check-umbrella
       - check-fail-ci
+    if: always() && !cancelled()
     steps:
-      - run: echo '### Good job! All the quick checks passed 🚀' >> $GITHUB_STEP_SUMMARY
+      - run: |
+          tee resultfile <<< '${{ toJSON(needs) }}'
+          cat resultfile | grep '"result": "failure"'
+          if [ $? -eq 0 ]; then
+            echo "### At least one required job failed ❌" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          else
+            echo '### Good job! All the required jobs passed 🚀' >> $GITHUB_STEP_SUMMARY
+          fi
