comment confirm

diff --git a/.github/workflows/tests-linux-stable.yml b/.github/workflows/tests-linux-stable.yml
--- a/.github/workflows/tests-linux-stable.yml
+++ b/.github/workflows/tests-linux-stable.yml
@@ -163,25 +163,25 @@ jobs:
   #         app-id: ${{ secrets.WORKFLOW_STOPPER_RUNNER_APP_ID }}
   #         app-key: ${{ secrets.WORKFLOW_STOPPER_RUNNER_APP_KEY }}
 
-  confirm-required-jobs-passed:
-    runs-on: ubuntu-latest
-    name: All tests passed
-    # If any new job gets added, be sure to add it to this array
-    needs:
-      [
-        test-linux-stable-int,
-        test-linux-stable-runtime-benchmarks,
-        test-linux-stable,
-        test-linux-stable-no-try-runtime,
-      ]
-    if: always() && !cancelled()
-    steps:
-      - run: |
-          tee resultfile <<< '${{ toJSON(needs) }}'
-          FAILURES=$(cat resultfile | grep '"result": "failure"' | wc -l)
-          if [ $FAILURES -gt 0 ]; then
-            echo "### At least one required job failed ❌" >> $GITHUB_STEP_SUMMARY
-            exit 1
-          else
-            echo '### Good job! All the required jobs passed 🚀' >> $GITHUB_STEP_SUMMARY
-          fi
+  # confirm-required-jobs-passed:
+  #   runs-on: ubuntu-latest
+  #   name: All tests passed
+  #   # If any new job gets added, be sure to add it to this array
+  #   needs:
+  #     [
+  #       test-linux-stable-int,
+  #       test-linux-stable-runtime-benchmarks,
+  #       test-linux-stable,
+  #       test-linux-stable-no-try-runtime,
+  #     ]
+  #   if: always() && !cancelled()
+  #   steps:
+  #     - run: |
+  #         tee resultfile <<< '${{ toJSON(needs) }}'
+  #         FAILURES=$(cat resultfile | grep '"result": "failure"' | wc -l)
+  #         if [ $FAILURES -gt 0 ]; then
+  #           echo "### At least one required job failed ❌" >> $GITHUB_STEP_SUMMARY
+  #           exit 1
+  #         else
+  #           echo '### Good job! All the required jobs passed 🚀' >> $GITHUB_STEP_SUMMARY
+  #         fi
